src/account/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView

from account import views
from account.decorators import anonymous_required
from account.forms import ResetPasswordEmailForm, ResetPasswordForm

app_name = "account"
urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path("sign-in/", views.sign_in, name="sign_in"),
    path(
        "logout/",
        login_required(
            LogoutView.as_view(template_name="account/logged_out.html")
        ),
        name="logout",
    ),
    path("overview/", views.overview, name="overview"),
    path("links/", views.links_list, name="links_list"),
    path("links/<int:page>/", views.links_list, name="links_list"),
    path("link/<str:alias>/", views.link_statistics, name="link_statistics"),
    path("link/update/<str:alias>/", views.update_link, name="update_link"),
    path("link/delete/<str:alias>/", views.delete_link, name="delete_link"),
    path("confirm-email/", views.confirm_email, name="confirm_email"),
    path(
        "new-confirmation-link/",
        views.new_confirmation_link,
        name="new_confirmation_link",
    ),
    path(
        "activate-email/<uidb64>/<token>/",
        views.activate_email,
        name="activate_email",
    ),
    path(
        "password-reset/",
        anonymous_required(
            PasswordResetView.as_view(
                form_class=ResetPasswordEmailForm,
                template_name="account/password_reset.html",
                email_template_name="account/email_password_reset_email.html",
                success_url=reverse_lazy("account:password_reset_done"),
            )
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        anonymous_required(
            PasswordResetConfirmView.as_view(
                form_class=ResetPasswordForm,
                template_name="account/password_reset_confirm.html",
                success_url=reverse_lazy("account:password_reset_complete"),
            )
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "privacy-policy/",
        TemplateView.as_view(template_name="account/privacy_policy.html"),
        name="privacy_policy",
    ),
    path(
        "terms-of-use/",
        TemplateView.as_view(template_name="account/terms_of_use.html"),
        name="terms_of_use",
    ),
]

src/shortener/urls.py
from django.urls import path

from . import views

app_name = "shortener"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:url_alias>/", views.shorten_redirect, name="shorten_redirect"),
]

src/shorty/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shortener.urls")),
    path("account/", include("account.urls")),
    path(
        "account/social-auth/",
        include("social_django.urls", namespace="social"),
    ),
    # path(
    #     ".well-known/acme-challenge/c3y8oJJ2G2WX8WtnfKv22MI-6i5TtqRa_Yd4OqDzu9o",
    #     TemplateView.as_view(
    #         template_name="common/certbot.txt", content_type="text/plain"
    #     ),
    # ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="foo,bar" />
        <meta name="description" content="foo" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
        <!-- fontawesom -->
        <script src="https://kit.fontawesome.com/142a68216d.js"
                crossorigin="anonymous"></script>
        <!-- normalize -->
        <link rel="stylesheet" href={% static 'normalize.css' %} />
        <!-- main css -->
        <link rel="stylesheet" href={% static 'main.css' %} />
        <meta name="google-site-verification"
              content="GpS_7xo4oZbiNKrgai4zmhQlXsZpqDpBNeJHpvk-yO0" />
        <title>
            {% block title %}
                Shorty
            {% endblock title %}
        </title>
    </head>
    <body>
        <header>
            {% comment %} navbar {% endcomment %}
            <nav class="nav" id="nav">
                <div class="section-center nav-center">
                    {% comment %} navlogo {% endcomment %}
                    <a href="{% url 'shortener:index' %}" class="nav-logo">
                        <img src="{% static 'logo.png' %}" alt="">
                    </a>
                    {% comment %} navbutton {% endcomment %}
                    <button class="icon-btn nav-btn" id="nav-btn">
                        <i class="fa-solid fa-bars"></i>
                    </button>
                    {% comment %} navlinks {% endcomment %}
                    <ul class="nav-links">
                        {% if user.is_authenticated %}
                            <li>
                                <a href="{% url 'account:links_list' %}" class="nav-link">links</a>
                            </li>
                            <li>
                                <a href="{% url 'account:overview' %}" class="nav-link">Overview</a>
                            </li>
                            <div class="dropdown">
                                <button class="drop-btn">
                                    {{ user.username }}
                                    <span><i class="fa-solid fa-caret-down"></i></span>
                                </button>
                                <div class="dropdown-content">
                                    {% comment %} <a href="#">settings</a> {% endcomment %}
                                    <a id="logout-btn-id">log out</a>
                                </div>
                            </div>
                        {% else %}
                            <li>
                                <a href={% url 'account:sign_in' %} class="nav-link">sign in</a>
                            </li>
                            <li>
                                <a href={% url 'account:sign_up' %} class="nav-link">sign up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            {% comment %} sidebar {% endcomment %}
            <aside class="sidebar" id="sidebar">
                <button class="icon-btn close-btn" id="close-btn">
                    <i class="fas fa-times"></i>
                </button>
                {% comment %} navbuttons {% endcomment %}
                {% if user.is_authenticated %}
                    <div class="sidebar-upper">
                        <div class="sidebar-profile">
                            <h5>{{ user.username }}</h5>
                        </div>
                        <a href="{% url 'account:links_list' %}">
                            <button class="btn btn-primary btn-block">links</button>
                        </a>
                        <a href="{% url 'account:overview' %}">
                            <button class="btn btn-primary btn-block">overview</button>
                        </a>
                    </div>
                    <div class="sidebar-lower">
                        <a href="{% url 'account:logout' %}" id="logout-btn-id-2">
                            <button class="btn btn-logout btn-block">log out</button>
                        </a>
                    </div>
                {% else %}
                    <div class="sidebar-upper">
                        <a href="{% url 'account:sign_in' %}">
                            <button class="btn btn-primary btn-block">sign in</button>
                        </a>
                        <a href="{% url 'account:sign_up' %}">
                            <button class="btn btn-primary btn-block">sign up</button>
                        </a>
                    </div>
                {% endif %}
            </aside>
        </header>
        {% block content %}
        {% endblock content %}
        <footer class="footer">
            <div class="section-center">
                <div class="footer-content">
                    <p>
                        &copy; <span id="date"></span> shorty. all rights reserved
                    </p>
                    <a href="{% url 'account:privacy_policy' %}" class="text-standard">Privacy Policy</a>
                    <a href="{% url 'account:terms_of_use' %}" class="text-standard">Terms Of Use</a>
                </div>
            </div>
        </footer>
        <script src="{% static 'main.js' %}"></script>
        {% block script %}
        {% endblock script %}
    </body>
</html>